version: '3.8'

services:
  app:
    build: .
    container_name: app_eventto
    environment:
      - DB_HOST=10.0.9.21
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      # Alternativas comentadas
      # - DB_USER=miguel
      # - DB_PASSWORD=32412294
      - DB_NAME=AppEvento
      - DB_POOL_MAX=5
      - DB_POOL_MIN=0
      - DB_POOL_ACQUIRE=30000
      - DB_POOL_IDLE=10000
      - DB_DIALECT=mysql
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/usr/src/app/uploads